"""ChangePilot data transfer objects."""

from __future__ import annotations

from app.domain.dto.approval import (
    ApprovalDecision,
    HumanApproval,
    HumanApprovalRequest,
)
from app.domain.dto.change_case import (
    SupplierEOLChangeCaseInput,
    SupplierEOLChangeCaseResult,
)
from app.domain.dto.eol_impact import (
    IMPACT_CAVEATS,
    AlternativeImpact,
    BOMQuantityEvidence,
    BOMQuantityImpact,
    InventoryImpact,
    ProductImpact,
    ProductionImpact,
    PurchaseImpact,
    SalesImpact,
    SupplierEOLImpactResult,
    SupplierImpact,
    WhereUsedPathEvidence,
)
from app.domain.dto.erp_facts import (
    InventoryFact,
    InventoryFactResult,
    ProductionRequirementFact,
    ProductionRequirementFactResult,
    PurchaseOrderFact,
    PurchaseOrderFactResult,
    SalesOrderFact,
    SalesOrderFactResult,
    SupplierFact,
    SupplierFactResult,
)
from app.domain.dto.execution import ExecutionResult, ExecutionResultStatus
from app.domain.dto.impact_metrics import (
    AlternativeAssessment,
    AlternativeClassification,
    InventoryMetrics,
    ProductionDemandClass,
    ProductionMetrics,
    ProductionRequirementAssessment,
    PurchaseInboundClass,
    PurchaseLineAssessment,
    PurchaseMetrics,
    PurchaseOrderAssessment,
    SalesExposureClass,
    SalesExposureMetrics,
    SalesLineAssessment,
    SalesOrderAssessment,
    SupplierEOLMetrics,
)
from app.domain.dto.product_structure import (
    AlternativeResult,
    AlternativeRow,
    BomExplosionResult,
    BomExplosionRow,
    PartRevisionDTO,
    WhereUsedResult,
    WhereUsedRow,
)
from app.domain.dto.review import ReviewDecision, ReviewResult
from app.domain.dto.strategy import (
    StrategyCandidate,
    StrategyGenerationResult,
    StrategyType,
)

__all__ = [
    "IMPACT_CAVEATS",
    "AlternativeAssessment",
    "AlternativeClassification",
    "AlternativeImpact",
    "AlternativeResult",
    "AlternativeRow",
    "ApprovalDecision",
    "BOMQuantityEvidence",
    "BOMQuantityImpact",
    "BomExplosionResult",
    "BomExplosionRow",
    "ExecutionResult",
    "ExecutionResultStatus",
    "HumanApproval",
    "HumanApprovalRequest",
    "InventoryFact",
    "InventoryFactResult",
    "InventoryImpact",
    "InventoryMetrics",
    "PartRevisionDTO",
    "ProductImpact",
    "ProductionDemandClass",
    "ProductionImpact",
    "ProductionMetrics",
    "ProductionRequirementAssessment",
    "ProductionRequirementFact",
    "ProductionRequirementFactResult",
    "PurchaseImpact",
    "PurchaseInboundClass",
    "PurchaseLineAssessment",
    "PurchaseMetrics",
    "PurchaseOrderAssessment",
    "PurchaseOrderFact",
    "PurchaseOrderFactResult",
    "ReviewDecision",
    "ReviewResult",
    "SalesExposureClass",
    "SalesExposureMetrics",
    "SalesImpact",
    "SalesLineAssessment",
    "SalesOrderAssessment",
    "SalesOrderFact",
    "SalesOrderFactResult",
    "StrategyCandidate",
    "StrategyGenerationResult",
    "StrategyType",
    "SupplierEOLChangeCaseInput",
    "SupplierEOLChangeCaseResult",
    "SupplierEOLImpactResult",
    "SupplierEOLMetrics",
    "SupplierFact",
    "SupplierFactResult",
    "SupplierImpact",
    "WhereUsedPathEvidence",
    "WhereUsedResult",
    "WhereUsedRow",
]
