"""Agent schema models: workflow runs, node steps and tool calls.

Field types, constraints and indexes follow design doc v0.4 as the single
source of truth:

- section 46: ``agent.agent_runs``
- section 47: ``agent.agent_steps``
- section 48: ``agent.tool_calls``

Conventions taken from the same document:

- section 6.1: internal ids are UUID (v4, generated by the application);
- section 7: timestamps with a time zone use ``timestamptz`` and are stored in
  UTC;
- section 25: ``created_at`` is ``NOT NULL`` and defaults to ``now()`` in the
  database;
- section 51: business foreign keys use ``ON DELETE RESTRICT``.

These tables are trace data only: they record which node ran and which tool was
called, never the model's private reasoning (v0.4 section 47). LangGraph
checkpoint tables are runtime data owned by the official checkpointer and are
deliberately not modelled here (v0.4 section 49).

``agent_runs.case_id`` is a plain UUID column, not a foreign key: the design
document marks it ``NOT NULL`` without an FK, and section 70 does not list it as
one either, so the agent schema stays decoupled from the ecm schema.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.postgres.base import Base

AGENT_SCHEMA = "agent"


class AgentRun(Base):
    """One agent workflow run for a change case (v0.4 section 46)."""

    __tablename__ = "agent_runs"
    __table_args__ = (
        CheckConstraint(
            "status IN ('RUNNING', 'WAITING_HUMAN', 'SUCCEEDED', 'FAILED', "
            "'CANCELLED')",
            name="ck_agent_runs_status",
        ),
        Index("ix_agent_runs_case_id", "case_id"),
        Index("ix_agent_runs_status", "status"),
        Index("ix_agent_runs_started_at", "started_at"),
        {"schema": AGENT_SCHEMA},
    )

    run_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    case_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    workflow_name: Mapped[str] = mapped_column(String(100), nullable=False)
    workflow_version: Mapped[str] = mapped_column(String(40), nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    model_provider: Mapped[str | None] = mapped_column(String(50), nullable=True)
    model_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    input_tokens: Mapped[int] = mapped_column(BigInteger, nullable=False)
    output_tokens: Mapped[int] = mapped_column(BigInteger, nullable=False)
    total_cost: Mapped[Decimal | None] = mapped_column(Numeric(18, 8), nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)


class AgentStep(Base):
    """One node execution inside an agent run (v0.4 section 47)."""

    __tablename__ = "agent_steps"
    __table_args__ = ({"schema": AGENT_SCHEMA},)

    step_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "agent.agent_runs.run_id",
            name="fk_agent_steps_run_id_agent_runs",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    node_name: Mapped[str] = mapped_column(String(100), nullable=False)
    agent_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    input_summary: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True
    )
    output_summary: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    latency_ms: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)


class ToolCall(Base):
    """One tool invocation made by an agent step (v0.4 section 48).

    Every WRITE tool call must additionally produce an audit event; that rule is
    enforced by the tool layer, not by a column constraint (v0.4 section 48).
    """

    __tablename__ = "tool_calls"
    __table_args__ = (
        CheckConstraint(
            "tool_mode IN ('READ', 'WRITE')",
            name="ck_tool_calls_tool_mode",
        ),
        CheckConstraint(
            "status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'BLOCKED')",
            name="ck_tool_calls_status",
        ),
        Index("ix_tool_calls_run_id", "run_id"),
        Index("ix_tool_calls_tool_name", "tool_name"),
        Index("ix_tool_calls_agent_name", "agent_name"),
        Index("ix_tool_calls_created_at", "created_at"),
        {"schema": AGENT_SCHEMA},
    )

    tool_call_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "agent.agent_runs.run_id",
            name="fk_tool_calls_run_id_agent_runs",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    step_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "agent.agent_steps.step_id",
            name="fk_tool_calls_step_id_agent_steps",
            ondelete="RESTRICT",
        ),
        nullable=True,
    )
    agent_name: Mapped[str] = mapped_column(String(100), nullable=False)
    tool_name: Mapped[str] = mapped_column(String(100), nullable=False)
    tool_mode: Mapped[str] = mapped_column(String(10), nullable=False)
    arguments: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    result_summary: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True
    )
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    latency_ms: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
