"""ECM schema models: engineering change case, request and impact analysis.

Field types, constraints and indexes follow design doc v0.4 as the single
source of truth:

- section 35: ``ecm.change_cases``
- section 36: ``ecm.engineering_change_requests``
- section 37: ``ecm.change_impacts``
- section 38: ``ecm.change_strategies``
- section 39: ``ecm.change_strategy_actions``
- section 40: ``ecm.change_reviews``
- section 41: ``ecm.engineering_change_orders``
- section 42: ``ecm.approval_records``
- section 43: ``ecm.bom_redlines``
- section 44: ``ecm.bom_redline_lines``
- section 45: ``ecm.execution_jobs``

Conventions taken from the same document:

- section 6.1: internal ids are UUID (v4, generated by the application);
- section 7: timestamps with a time zone use ``timestamptz`` and are stored in
  UTC;
- section 8: quantities and amounts use ``numeric(18, 4)``;
- section 9: JSON is only used for event payloads and analysis evidence, here
  ``raw_event`` and ``evidence`` (``jsonb``);
- section 25: ``created_at`` / ``updated_at`` are ``NOT NULL`` and default to
  ``now()`` in the database;
- section 51: business foreign keys use ``ON DELETE RESTRICT``;
- section 52: product structure identifiers such as ``subject_part_number``
  belong to Neo4j, so they are stored as business keys without a database
  foreign key.

Only real foreign keys express the case -> request -> impact chain; no extra
ORM relationship is invented beyond the document.

Constraint and index names are written out explicitly so Alembic migrations
stay reviewable and reversible.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    CHAR,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.postgres.base import Base

ECM_SCHEMA = "ecm"


class ChangeCase(Base):
    """Technical case container for one agent workflow instance (section 35)."""

    __tablename__ = "change_cases"
    __table_args__ = (
        UniqueConstraint("case_number", name="uq_change_cases_case_number"),
        UniqueConstraint("idempotency_key", name="uq_change_cases_idempotency_key"),
        CheckConstraint(
            "case_type IN ('SUPPLIER_EOL', 'QUALITY_ISSUE', 'CUSTOMER_CHANGE', "
            "'COST_REDUCTION', 'REGULATORY_CHANGE', 'MATERIAL_SUBSTITUTION')",
            name="ck_change_cases_case_type",
        ),
        CheckConstraint(
            "status IN ('RECEIVED', 'ANALYZING', 'PLANNING', 'WAITING_APPROVAL', "
            "'APPROVED', 'EXECUTING', 'COMPLETED', 'REJECTED', 'FAILED', 'CANCELLED')",
            name="ck_change_cases_status",
        ),
        Index("ix_change_cases_status", "status"),
        Index("ix_change_cases_case_type", "case_type"),
        Index("ix_change_cases_created_at", "created_at"),
        {"schema": ECM_SCHEMA},
    )

    case_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    case_number: Mapped[str] = mapped_column(String(40), nullable=False)
    case_type: Mapped[str] = mapped_column(String(40), nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    source_type: Mapped[str] = mapped_column(String(30), nullable=False)
    raw_event: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    idempotency_key: Mapped[str] = mapped_column(String(100), nullable=False)
    created_by: Mapped[str] = mapped_column(String(100), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    closed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


class EngineeringChangeRequest(Base):
    """Engineering change request belonging to one case (v0.4 section 36).

    ``case_id`` is ``UNIQUE``: one case holds at most one request.
    ``subject_part_number`` / ``subject_revision_code`` are Neo4j business
    identifiers without a database foreign key (v0.4 section 52).
    """

    __tablename__ = "engineering_change_requests"
    __table_args__ = (
        UniqueConstraint("ecr_number", name="uq_engineering_change_requests_number"),
        UniqueConstraint("case_id", name="uq_engineering_change_requests_case_id"),
        CheckConstraint(
            "priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name="ck_engineering_change_requests_priority",
        ),
        CheckConstraint(
            "status IN ('DRAFT', 'OPEN', 'ANALYZING', 'PLANNING', "
            "'WAITING_APPROVAL', 'APPROVED', 'REJECTED', 'CLOSED')",
            name="ck_engineering_change_requests_status",
        ),
        Index(
            "ix_engineering_change_requests_subject_part_number",
            "subject_part_number",
        ),
        Index("ix_engineering_change_requests_status", "status"),
        Index("ix_engineering_change_requests_priority", "priority"),
        Index("ix_engineering_change_requests_created_at", "created_at"),
        {"schema": ECM_SCHEMA},
    )

    ecr_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    ecr_number: Mapped[str] = mapped_column(String(40), nullable=False)
    case_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.change_cases.case_id",
            name="fk_engineering_change_requests_case_id_change_cases",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    change_type: Mapped[str] = mapped_column(String(40), nullable=False)
    source_type: Mapped[str] = mapped_column(String(30), nullable=False)
    subject_part_number: Mapped[str] = mapped_column(String(64), nullable=False)
    subject_revision_code: Mapped[str | None] = mapped_column(
        String(16), nullable=True
    )
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    priority: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    requested_by: Mapped[str] = mapped_column(String(100), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ChangeImpact(Base):
    """One object found by one impact analysis run (v0.4 section 37).

    Re-running the analysis creates a new ``analysis_run_id`` instead of
    overwriting results, so old rows stay for audit and evaluation; the unique
    constraint only removes duplicates inside a single run.
    """

    __tablename__ = "change_impacts"
    __table_args__ = (
        # Shortened on purpose: the fully spelled out form
        # (uq_change_impacts_analysis_run_id_object_type_object_key_impact_type)
        # is 68 bytes and would be truncated by the 63 byte identifier limit.
        UniqueConstraint(
            "analysis_run_id",
            "object_type",
            "object_key",
            "impact_type",
            name="uq_change_impacts_analysis_run_object_impact",
        ),
        CheckConstraint(
            "object_type IN ('PART', 'PART_REVISION', 'ASSEMBLY', 'PRODUCT', "
            "'BOM_VERSION', 'INVENTORY', 'PURCHASE_ORDER', 'PRODUCTION_ORDER', "
            "'SALES_ORDER')",
            name="ck_change_impacts_object_type",
        ),
        CheckConstraint(
            "severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name="ck_change_impacts_severity",
        ),
        Index("ix_change_impacts_ecr_id", "ecr_id"),
        Index("ix_change_impacts_analysis_run_id", "analysis_run_id"),
        Index("ix_change_impacts_object_type_object_key", "object_type", "object_key"),
        Index("ix_change_impacts_severity", "severity"),
        {"schema": ECM_SCHEMA},
    )

    impact_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    ecr_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.engineering_change_requests.ecr_id",
            name="fk_change_impacts_ecr_id_engineering_change_requests",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    analysis_run_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    object_type: Mapped[str] = mapped_column(String(40), nullable=False)
    object_key: Mapped[str] = mapped_column(String(150), nullable=False)
    impact_type: Mapped[str] = mapped_column(String(40), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    evidence: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ChangeStrategy(Base):
    """A candidate change strategy for one request (v0.4 section 38).

    ``cost_delta`` may be negative (v0.4 section 38), so no sign check is
    applied to it; only ``inventory_writeoff_cost`` is constrained.
    ``replacement_part_number`` / ``replacement_revision_code`` are Neo4j
    business identifiers without a database foreign key (v0.4 section 52).
    """

    __tablename__ = "change_strategies"
    __table_args__ = (
        UniqueConstraint(
            "ecr_id",
            "strategy_code",
            name="uq_change_strategies_ecr_id_strategy_code",
        ),
        CheckConstraint(
            "strategy_type IN ('IMMEDIATE_REPLACEMENT', 'INVENTORY_RUN_OUT', "
            "'SPLIT_EFFECTIVITY', 'LAST_TIME_BUY')",
            name="ck_change_strategies_strategy_type",
        ),
        CheckConstraint(
            "status IN ('CANDIDATE', 'RECOMMENDED', 'SELECTED', "
            "'REJECTED', 'SUPERSEDED')",
            name="ck_change_strategies_status",
        ),
        CheckConstraint(
            "inventory_writeoff_cost >= 0",
            name="ck_change_strategies_writeoff_cost_non_negative",
        ),
        {"schema": ECM_SCHEMA},
    )

    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    ecr_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.engineering_change_requests.ecr_id",
            name="fk_change_strategies_ecr_id_engineering_change_requests",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    strategy_code: Mapped[str] = mapped_column(String(30), nullable=False)
    strategy_type: Mapped[str] = mapped_column(String(40), nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    effective_from: Mapped[date | None] = mapped_column(Date, nullable=True)
    replacement_part_number: Mapped[str | None] = mapped_column(
        String(64), nullable=True
    )
    replacement_revision_code: Mapped[str | None] = mapped_column(
        String(16), nullable=True
    )
    risk_level: Mapped[str] = mapped_column(String(20), nullable=False)
    cost_delta: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    inventory_writeoff_cost: Mapped[Decimal] = mapped_column(
        Numeric(18, 4), nullable=False
    )
    currency: Mapped[str] = mapped_column(CHAR(3), nullable=False)
    details: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ChangeStrategyAction(Base):
    """One structured action of a change strategy (v0.4 section 39).

    The planner may not invent unregistered action types, so ``action_type`` is
    constrained to the values listed in the design document. ``target_key``
    carries a business identifier (for example a Neo4j part number), so it has
    no database foreign key.
    """

    __tablename__ = "change_strategy_actions"
    __table_args__ = (
        UniqueConstraint(
            "strategy_id",
            "sequence_no",
            name="uq_change_strategy_actions_strategy_id_sequence_no",
        ),
        CheckConstraint(
            "action_type IN ('CREATE_BOM_REDLINE', 'SET_EFFECTIVITY', "
            "'BLOCK_PRODUCTION_ORDER', 'NOTIFY_OWNER', 'CREATE_ECO_DRAFT')",
            name="ck_change_strategy_actions_action_type",
        ),
        CheckConstraint(
            "sequence_no > 0",
            name="ck_change_strategy_actions_sequence_no_positive",
        ),
        {"schema": ECM_SCHEMA},
    )

    action_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.change_strategies.strategy_id",
            name="fk_change_strategy_actions_strategy_id_change_strategies",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    sequence_no: Mapped[int] = mapped_column(Integer, nullable=False)
    action_type: Mapped[str] = mapped_column(String(40), nullable=False)
    target_type: Mapped[str] = mapped_column(String(40), nullable=False)
    target_key: Mapped[str] = mapped_column(String(150), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    requires_approval: Mapped[bool] = mapped_column(Boolean, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ChangeReview(Base):
    """Risk review result for one change strategy (v0.4 section 40).

    History is append-only: older reviews are never overwritten, which is why
    the table carries ``review_run_id`` and only ``created_at``.
    """

    __tablename__ = "change_reviews"
    __table_args__ = (
        CheckConstraint(
            "decision IN ('PASS', 'REWORK', 'HUMAN_REVIEW', 'BLOCK')",
            name="ck_change_reviews_decision",
        ),
        {"schema": ECM_SCHEMA},
    )

    review_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.change_strategies.strategy_id",
            name="fk_change_reviews_strategy_id_change_strategies",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    review_run_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    decision: Mapped[str] = mapped_column(String(30), nullable=False)
    risk_level: Mapped[str] = mapped_column(String(20), nullable=False)
    evidence_complete: Mapped[bool] = mapped_column(Boolean, nullable=False)
    issues: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class EngineeringChangeOrder(Base):
    """Engineering change order created from a selected strategy (section 41).

    The documented business rules (only APPROVED may move to EXECUTING, and
    WAITING_APPROVAL -> APPROVED requires a real approval record) are state
    transition rules and cannot be expressed as column constraints; the domain
    service owns them.
    """

    __tablename__ = "engineering_change_orders"
    __table_args__ = (
        UniqueConstraint(
            "eco_number", name="uq_engineering_change_orders_eco_number"
        ),
        CheckConstraint(
            "status IN ('DRAFT', 'WAITING_APPROVAL', 'APPROVED', 'EXECUTING', "
            "'EXECUTED', 'EXECUTION_FAILED', 'REJECTED', 'CANCELLED')",
            name="ck_engineering_change_orders_status",
        ),
        {"schema": ECM_SCHEMA},
    )

    eco_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    eco_number: Mapped[str] = mapped_column(String(40), nullable=False)
    ecr_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        # The name omits the referenced table: the full pattern would be 66
        # bytes and PostgreSQL identifiers are limited to 63 bytes.
        ForeignKey(
            "ecm.engineering_change_requests.ecr_id",
            name="fk_engineering_change_orders_ecr_id",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    selected_strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.change_strategies.strategy_id",
            name="fk_engineering_change_orders_selected_strategy_id",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    effective_from: Mapped[date] = mapped_column(Date, nullable=False)
    approved_by: Mapped[str | None] = mapped_column(String(100), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    executed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ApprovalRecord(Base):
    """Human approval decision for an ECO (v0.4 section 42).

    ``approval_type`` has no CHECK on purpose: the design document describes it
    as a roadmap ("MVP: one ENGINEERING_CHANGE_APPROVAL; V2 may add ...") rather
    than as a closed value list, so no value domain is invented here.
    """

    __tablename__ = "approval_records"
    __table_args__ = (
        CheckConstraint(
            "decision IN ('APPROVED', 'REJECTED', 'REWORK')",
            name="ck_approval_records_decision",
        ),
        {"schema": ECM_SCHEMA},
    )

    approval_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    eco_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.engineering_change_orders.eco_id",
            name="fk_approval_records_eco_id_engineering_change_orders",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    approval_type: Mapped[str] = mapped_column(String(40), nullable=False)
    approver_id: Mapped[str] = mapped_column(String(100), nullable=False)
    decision: Mapped[str] = mapped_column(String(20), nullable=False)
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    decided_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class BOMRedline(Base):
    """Draft BOM change against a released BOM (v0.4 section 43).

    ``source_bom_version_id`` / ``target_bom_version_id`` are UUIDs of objects
    that live in Neo4j, so there is no database foreign key; the PLM tool checks
    existence on creation (v0.4 section 43).
    """

    __tablename__ = "bom_redlines"
    __table_args__ = (
        CheckConstraint(
            "status IN ('DRAFT', 'APPROVED', 'APPLIED', 'REJECTED', 'FAILED')",
            name="ck_bom_redlines_status",
        ),
        {"schema": ECM_SCHEMA},
    )

    redline_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    eco_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.engineering_change_orders.eco_id",
            name="fk_bom_redlines_eco_id_engineering_change_orders",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    source_bom_version_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )
    target_bom_version_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    applied_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


class BOMRedlineLine(Base):
    """One ADD / REMOVE / REPLACE / UPDATE_QUANTITY line (v0.4 section 44).

    The document delegates the cross-field conditions (REPLACE needs old and new
    part number, ADD needs a new one, REMOVE needs an old one) to Pydantic and
    the domain service, so no CHECK is created for them. The part numbers and
    ``source_bom_line_id`` refer to Neo4j objects and have no database foreign
    key.
    """

    __tablename__ = "bom_redline_lines"
    __table_args__ = (
        CheckConstraint(
            "action_type IN ('ADD', 'REMOVE', 'REPLACE', 'UPDATE_QUANTITY')",
            name="ck_bom_redline_lines_action_type",
        ),
        CheckConstraint(
            "sequence_no > 0",
            name="ck_bom_redline_lines_sequence_no_positive",
        ),
        {"schema": ECM_SCHEMA},
    )

    redline_line_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    redline_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.bom_redlines.redline_id",
            name="fk_bom_redline_lines_redline_id_bom_redlines",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    sequence_no: Mapped[int] = mapped_column(Integer, nullable=False)
    action_type: Mapped[str] = mapped_column(String(30), nullable=False)
    source_bom_line_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    old_part_number: Mapped[str | None] = mapped_column(String(64), nullable=True)
    old_revision_code: Mapped[str | None] = mapped_column(String(16), nullable=True)
    new_part_number: Mapped[str | None] = mapped_column(String(64), nullable=True)
    new_revision_code: Mapped[str | None] = mapped_column(String(16), nullable=True)
    old_quantity: Mapped[Decimal | None] = mapped_column(Numeric(18, 4), nullable=True)
    new_quantity: Mapped[Decimal | None] = mapped_column(Numeric(18, 4), nullable=True)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ExecutionJob(Base):
    """Controlled, retryable, idempotent cross-database execution (section 45).

    PostgreSQL and Neo4j share no ACID transaction, so the job is the unit of
    coordination: a unique ``idempotency_key`` makes a retry of the same job
    safe. Only the data model is created here, not the executor.
    """

    __tablename__ = "execution_jobs"
    __table_args__ = (
        UniqueConstraint(
            "idempotency_key", name="uq_execution_jobs_idempotency_key"
        ),
        CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name="ck_execution_jobs_status",
        ),
        {"schema": ECM_SCHEMA},
    )

    execution_job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    eco_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "ecm.engineering_change_orders.eco_id",
            name="fk_execution_jobs_eco_id_engineering_change_orders",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    action_type: Mapped[str] = mapped_column(String(40), nullable=False)
    idempotency_key: Mapped[str] = mapped_column(String(120), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
