"""ERP schema models: supplier master data, supplier parts and inventory.

Field types, constraints and indexes follow design doc v0.4 as the single
source of truth:

- section 26: ``erp.suppliers``
- section 27: ``erp.supplier_parts``
- section 28: ``erp.inventory_balances``
- section 29: ``erp.purchase_orders``
- section 30: ``erp.purchase_order_lines``
- section 31: ``erp.production_orders``
- section 32: ``erp.production_material_requirements``
- section 33: ``erp.sales_orders``
- section 34: ``erp.sales_order_lines``

Conventions taken from the same document:

- section 6.1: internal ids are UUID (v4, generated by the application);
- section 7: timestamps with a time zone use ``timestamptz`` and are stored in
  UTC; pure calendar dates use ``date``;
- section 8: quantities and amounts use ``numeric(18, 4)``, currency uses
  ``char(3)``, and ``float`` is never used;
- section 25: ``created_at`` / ``updated_at`` are ``NOT NULL`` and default to
  ``now()`` in the database;
- section 51: business foreign keys use ``ON DELETE RESTRICT``.

``part_number`` / ``revision_code`` are cross-database business keys pointing at
the Neo4j product structure, so they are intentionally plain columns without a
foreign key (v0.4 section 52).

Constraint and index names are written out explicitly so Alembic migrations
stay reviewable and reversible.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    CHAR,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.postgres.base import Base

ERP_SCHEMA = "erp"


class Supplier(Base):
    """A supplier of the simulated company (v0.4 section 26)."""

    __tablename__ = "suppliers"
    __table_args__ = (
        UniqueConstraint("supplier_code", name="uq_suppliers_supplier_code"),
        CheckConstraint(
            "status IN ('ACTIVE', 'BLOCKED', 'PHASE_OUT')",
            name="ck_suppliers_status",
        ),
        CheckConstraint(
            "quality_rating >= 0 AND quality_rating <= 100",
            name="ck_suppliers_quality_rating_range",
        ),
        CheckConstraint(
            "delivery_rating >= 0 AND delivery_rating <= 100",
            name="ck_suppliers_delivery_rating_range",
        ),
        Index("ix_suppliers_status", "status"),
        {"schema": ERP_SCHEMA},
    )

    supplier_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    supplier_code: Mapped[str] = mapped_column(String(32), nullable=False)
    supplier_name: Mapped[str] = mapped_column(String(200), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    quality_rating: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False)
    delivery_rating: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class SupplierPart(Base):
    """Supply relationship between a supplier and a part (v0.4 section 27)."""

    __tablename__ = "supplier_parts"
    __table_args__ = (
        UniqueConstraint(
            "supplier_id",
            "manufacturer_part_number",
            name="uq_supplier_parts_supplier_manufacturer_part_number",
        ),
        CheckConstraint(
            "qualification_status IN ('QUALIFIED', 'CONDITIONAL', 'UNQUALIFIED')",
            name="ck_supplier_parts_qualification_status",
        ),
        CheckConstraint(
            "status IN ('ACTIVE', 'LAST_TIME_BUY', 'EOL', 'BLOCKED')",
            name="ck_supplier_parts_status",
        ),
        CheckConstraint(
            "unit_price >= 0",
            name="ck_supplier_parts_unit_price_non_negative",
        ),
        CheckConstraint(
            "lead_time_days >= 0",
            name="ck_supplier_parts_lead_time_days_non_negative",
        ),
        CheckConstraint(
            "minimum_order_qty > 0",
            name="ck_supplier_parts_minimum_order_qty_positive",
        ),
        CheckConstraint(
            "last_time_buy_date IS NULL OR eol_date IS NULL "
            "OR last_time_buy_date <= eol_date",
            name="ck_supplier_parts_last_time_buy_before_eol",
        ),
        Index("ix_supplier_parts_part_number", "part_number"),
        Index(
            "ix_supplier_parts_part_number_qualification_status",
            "part_number",
            "qualification_status",
        ),
        Index("ix_supplier_parts_supplier_id", "supplier_id"),
        Index("ix_supplier_parts_eol_date", "eol_date"),
        {"schema": ERP_SCHEMA},
    )

    supplier_part_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    supplier_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "erp.suppliers.supplier_id",
            name="fk_supplier_parts_supplier_id_suppliers",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    part_number: Mapped[str] = mapped_column(String(64), nullable=False)
    revision_code: Mapped[str | None] = mapped_column(String(16), nullable=True)
    manufacturer_part_number: Mapped[str] = mapped_column(String(100), nullable=False)
    qualification_status: Mapped[str] = mapped_column(String(20), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    currency: Mapped[str] = mapped_column(CHAR(3), nullable=False)
    lead_time_days: Mapped[int] = mapped_column(Integer, nullable=False)
    minimum_order_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    last_time_buy_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    eol_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class InventoryBalance(Base):
    """Inventory balance per plant, warehouse, part and revision (section 28)."""

    __tablename__ = "inventory_balances"
    __table_args__ = (
        UniqueConstraint(
            "plant_code",
            "warehouse_code",
            "part_number",
            "revision_code",
            name="uq_inventory_balances_plant_warehouse_part_revision",
        ),
        CheckConstraint("qty_on_hand >= 0", name="ck_inventory_balances_qty_on_hand"),
        CheckConstraint(
            "qty_reserved >= 0", name="ck_inventory_balances_qty_reserved"
        ),
        CheckConstraint(
            "qty_reserved <= qty_on_hand",
            name="ck_inventory_balances_qty_reserved_lte_on_hand",
        ),
        CheckConstraint("unit_cost >= 0", name="ck_inventory_balances_unit_cost"),
        Index("ix_inventory_balances_part_number", "part_number"),
        Index(
            "ix_inventory_balances_part_number_revision_code",
            "part_number",
            "revision_code",
        ),
        Index("ix_inventory_balances_plant_code", "plant_code"),
        {"schema": ERP_SCHEMA},
    )

    inventory_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    plant_code: Mapped[str] = mapped_column(String(20), nullable=False)
    warehouse_code: Mapped[str] = mapped_column(String(20), nullable=False)
    part_number: Mapped[str] = mapped_column(String(64), nullable=False)
    revision_code: Mapped[str] = mapped_column(String(16), nullable=False)
    qty_on_hand: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    qty_reserved: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    unit_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    currency: Mapped[str] = mapped_column(CHAR(3), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class PurchaseOrder(Base):
    """A purchase order placed at a supplier (v0.4 section 29)."""

    __tablename__ = "purchase_orders"
    __table_args__ = (
        UniqueConstraint("po_number", name="uq_purchase_orders_po_number"),
        CheckConstraint(
            "status IN ('DRAFT', 'OPEN', 'PARTIALLY_RECEIVED', "
            "'COMPLETED', 'CANCELLED', 'BLOCKED')",
            name="ck_purchase_orders_status",
        ),
        Index("ix_purchase_orders_supplier_id", "supplier_id"),
        Index("ix_purchase_orders_status", "status"),
        Index("ix_purchase_orders_expected_date", "expected_date"),
        {"schema": ERP_SCHEMA},
    )

    po_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    po_number: Mapped[str] = mapped_column(String(40), nullable=False)
    supplier_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "erp.suppliers.supplier_id",
            name="fk_purchase_orders_supplier_id_suppliers",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    order_date: Mapped[date] = mapped_column(Date, nullable=False)
    expected_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    currency: Mapped[str] = mapped_column(CHAR(3), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class PurchaseOrderLine(Base):
    """A single line of a purchase order (v0.4 section 30).

    ``part_number`` / ``revision_code`` point at the Neo4j product structure,
    so they carry no database foreign key (v0.4 section 52).
    """

    __tablename__ = "purchase_order_lines"
    __table_args__ = (
        UniqueConstraint(
            "po_id", "line_number", name="uq_purchase_order_lines_po_id_line_number"
        ),
        CheckConstraint(
            "line_number > 0", name="ck_purchase_order_lines_line_number_positive"
        ),
        CheckConstraint(
            "ordered_qty > 0", name="ck_purchase_order_lines_ordered_qty_positive"
        ),
        CheckConstraint(
            "received_qty >= 0",
            name="ck_purchase_order_lines_received_qty_non_negative",
        ),
        CheckConstraint(
            "received_qty <= ordered_qty",
            name="ck_purchase_order_lines_received_qty_lte_ordered",
        ),
        CheckConstraint(
            "unit_price >= 0", name="ck_purchase_order_lines_unit_price_non_negative"
        ),
        Index("ix_purchase_order_lines_part_number", "part_number"),
        Index(
            "ix_purchase_order_lines_part_number_revision_code",
            "part_number",
            "revision_code",
        ),
        Index("ix_purchase_order_lines_status", "status"),
        Index("ix_purchase_order_lines_expected_date", "expected_date"),
        {"schema": ERP_SCHEMA},
    )

    po_line_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    po_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "erp.purchase_orders.po_id",
            name="fk_purchase_order_lines_po_id_purchase_orders",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)
    part_number: Mapped[str] = mapped_column(String(64), nullable=False)
    revision_code: Mapped[str] = mapped_column(String(16), nullable=False)
    ordered_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    received_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    expected_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ProductionOrder(Base):
    """A production order for one product revision (v0.4 section 31).

    ``product_part_number`` / ``product_revision`` identify the manufactured
    product in the Neo4j structure, so they are business keys without a
    database foreign key (v0.4 section 52).
    """

    __tablename__ = "production_orders"
    __table_args__ = (
        UniqueConstraint("order_number", name="uq_production_orders_order_number"),
        CheckConstraint(
            "status IN ('PLANNED', 'RELEASED', 'IN_PROGRESS', "
            "'COMPLETED', 'BLOCKED', 'CANCELLED')",
            name="ck_production_orders_status",
        ),
        CheckConstraint(
            "planned_qty > 0", name="ck_production_orders_planned_qty_positive"
        ),
        CheckConstraint(
            "completed_qty >= 0",
            name="ck_production_orders_completed_qty_non_negative",
        ),
        CheckConstraint(
            "completed_qty <= planned_qty",
            name="ck_production_orders_completed_qty_lte_planned",
        ),
        CheckConstraint(
            "planned_start <= planned_end",
            name="ck_production_orders_planned_window",
        ),
        Index(
            "ix_production_orders_product_part_number_product_revision",
            "product_part_number",
            "product_revision",
        ),
        Index("ix_production_orders_status", "status"),
        Index("ix_production_orders_planned_start", "planned_start"),
        Index("ix_production_orders_planned_end", "planned_end"),
        {"schema": ERP_SCHEMA},
    )

    production_order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    order_number: Mapped[str] = mapped_column(String(40), nullable=False)
    product_part_number: Mapped[str] = mapped_column(String(64), nullable=False)
    product_revision: Mapped[str] = mapped_column(String(16), nullable=False)
    planned_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    completed_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    planned_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    planned_end: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ProductionMaterialRequirement(Base):
    """Frozen material requirement of a production order (v0.4 section 32).

    These rows are the deterministic BOM explosion result captured when the
    order is released, and they are kept as historical transaction fact:

    - later BOM changes in Neo4j must never rewrite them;
    - the current Neo4j BOM must never be used to reconstruct them
      (v0.3 section 15, v0.4 section 32).

    ``part_number`` / ``revision_code`` and the quantities are therefore stored
    directly on this table. They are Neo4j business identifiers, so no
    cross-database foreign key is created (v0.4 section 52).
    """

    __tablename__ = "production_material_requirements"
    __table_args__ = (
        # The unique name is shortened on purpose: identifiers are limited to
        # 63 bytes in PostgreSQL and the fully spelled out form would exceed it.
        UniqueConstraint(
            "production_order_id",
            "line_number",
            name="uq_production_material_requirements_order_line_number",
        ),
        CheckConstraint(
            "line_number > 0",
            name="ck_production_material_requirements_line_number_positive",
        ),
        CheckConstraint(
            "required_qty > 0",
            name="ck_production_material_requirements_required_qty_positive",
        ),
        CheckConstraint(
            "reserved_qty >= 0",
            name="ck_production_material_requirements_reserved_qty_non_negative",
        ),
        CheckConstraint(
            "issued_qty >= 0",
            name="ck_production_material_requirements_issued_qty_non_negative",
        ),
        CheckConstraint(
            "reserved_qty <= required_qty",
            name="ck_production_material_requirements_reserved_qty_lte_required",
        ),
        CheckConstraint(
            "issued_qty <= required_qty",
            name="ck_production_material_requirements_issued_qty_lte_required",
        ),
        Index(
            "ix_production_material_requirements_part_number_revision_code",
            "part_number",
            "revision_code",
        ),
        Index(
            "ix_production_material_requirements_production_order_id",
            "production_order_id",
        ),
        {"schema": ERP_SCHEMA},
    )

    requirement_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    production_order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "erp.production_orders.production_order_id",
            name="fk_production_material_requirements_production_orders",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)
    part_number: Mapped[str] = mapped_column(String(64), nullable=False)
    revision_code: Mapped[str] = mapped_column(String(16), nullable=False)
    required_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    reserved_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    issued_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class SalesOrder(Base):
    """A customer sales order (v0.4 section 33).

    ``customer_code`` is a stable business code: v0.4 defines no customer table,
    so there is deliberately no foreign key for it.
    """

    __tablename__ = "sales_orders"
    __table_args__ = (
        UniqueConstraint("order_number", name="uq_sales_orders_order_number"),
        CheckConstraint(
            "status IN ('DRAFT', 'OPEN', 'CONFIRMED', "
            "'PARTIALLY_DELIVERED', 'COMPLETED', 'CANCELLED')",
            name="ck_sales_orders_status",
        ),
        Index("ix_sales_orders_customer_code", "customer_code"),
        Index("ix_sales_orders_status", "status"),
        Index("ix_sales_orders_requested_delivery_date", "requested_delivery_date"),
        {"schema": ERP_SCHEMA},
    )

    sales_order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    order_number: Mapped[str] = mapped_column(String(40), nullable=False)
    customer_code: Mapped[str] = mapped_column(String(40), nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False)
    order_date: Mapped[date] = mapped_column(Date, nullable=False)
    requested_delivery_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class SalesOrderLine(Base):
    """A single line of a sales order (v0.4 section 34).

    ``product_part_number`` / ``product_revision`` point at the Neo4j product
    structure, so they carry no database foreign key (v0.4 section 52).
    """

    __tablename__ = "sales_order_lines"
    __table_args__ = (
        UniqueConstraint(
            "sales_order_id",
            "line_number",
            name="uq_sales_order_lines_sales_order_id_line_number",
        ),
        CheckConstraint(
            "line_number > 0", name="ck_sales_order_lines_line_number_positive"
        ),
        CheckConstraint(
            "ordered_qty > 0", name="ck_sales_order_lines_ordered_qty_positive"
        ),
        CheckConstraint(
            "delivered_qty >= 0",
            name="ck_sales_order_lines_delivered_qty_non_negative",
        ),
        CheckConstraint(
            "delivered_qty <= ordered_qty",
            name="ck_sales_order_lines_delivered_qty_lte_ordered",
        ),
        Index(
            "ix_sales_order_lines_product_part_number_product_revision",
            "product_part_number",
            "product_revision",
        ),
        Index(
            "ix_sales_order_lines_requested_delivery_date",
            "requested_delivery_date",
        ),
        {"schema": ERP_SCHEMA},
    )

    sales_order_line_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True
    )
    sales_order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "erp.sales_orders.sales_order_id",
            name="fk_sales_order_lines_sales_order_id_sales_orders",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)
    product_part_number: Mapped[str] = mapped_column(String(64), nullable=False)
    product_revision: Mapped[str] = mapped_column(String(16), nullable=False)
    ordered_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    delivered_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    requested_delivery_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
