"""create erp master tables

Creates the first ERP master data tables described in design doc v0.4:
erp.suppliers (section 26), erp.supplier_parts (section 27) and
erp.inventory_balances (section 28).

The upgrade creates suppliers before supplier_parts so the foreign key target
exists; the downgrade drops them in the opposite order.

Revision ID: 0002_create_erp_master_tables
Revises: 0001_create_base_schemas
Create Date: 2026-09-20 19:27:03.312555

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002_create_erp_master_tables'
down_revision: str | Sequence[str] | None = '0001_create_base_schemas'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_balances',
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('plant_code', sa.String(length=20), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('revision_code', sa.String(length=16), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty_on_hand >= 0', name='ck_inventory_balances_qty_on_hand'),
    sa.CheckConstraint('qty_reserved <= qty_on_hand', name='ck_inventory_balances_qty_reserved_lte_on_hand'),
    sa.CheckConstraint('qty_reserved >= 0', name='ck_inventory_balances_qty_reserved'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_inventory_balances_unit_cost'),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('plant_code', 'warehouse_code', 'part_number', 'revision_code', name='uq_inventory_balances_plant_warehouse_part_revision'),
    schema='erp'
    )
    op.create_index('ix_inventory_balances_part_number', 'inventory_balances', ['part_number'], unique=False, schema='erp')
    op.create_index('ix_inventory_balances_part_number_revision_code', 'inventory_balances', ['part_number', 'revision_code'], unique=False, schema='erp')
    op.create_index('ix_inventory_balances_plant_code', 'inventory_balances', ['plant_code'], unique=False, schema='erp')
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.String(length=32), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quality_rating', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('delivery_rating', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'BLOCKED', 'PHASE_OUT')", name='ck_suppliers_status'),
    sa.CheckConstraint('delivery_rating >= 0 AND delivery_rating <= 100', name='ck_suppliers_delivery_rating_range'),
    sa.CheckConstraint('quality_rating >= 0 AND quality_rating <= 100', name='ck_suppliers_quality_rating_range'),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('supplier_code', name='uq_suppliers_supplier_code'),
    schema='erp'
    )
    op.create_index('ix_suppliers_status', 'suppliers', ['status'], unique=False, schema='erp')
    op.create_table('supplier_parts',
    sa.Column('supplier_part_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('revision_code', sa.String(length=16), nullable=True),
    sa.Column('manufacturer_part_number', sa.String(length=100), nullable=False),
    sa.Column('qualification_status', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('minimum_order_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_time_buy_date', sa.Date(), nullable=True),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("qualification_status IN ('QUALIFIED', 'CONDITIONAL', 'UNQUALIFIED')", name='ck_supplier_parts_qualification_status'),
    sa.CheckConstraint("status IN ('ACTIVE', 'LAST_TIME_BUY', 'EOL', 'BLOCKED')", name='ck_supplier_parts_status'),
    sa.CheckConstraint('last_time_buy_date IS NULL OR eol_date IS NULL OR last_time_buy_date <= eol_date', name='ck_supplier_parts_last_time_buy_before_eol'),
    sa.CheckConstraint('lead_time_days >= 0', name='ck_supplier_parts_lead_time_days_non_negative'),
    sa.CheckConstraint('minimum_order_qty > 0', name='ck_supplier_parts_minimum_order_qty_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_supplier_parts_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['supplier_id'], ['erp.suppliers.supplier_id'], name='fk_supplier_parts_supplier_id_suppliers', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_part_id'),
    sa.UniqueConstraint('supplier_id', 'manufacturer_part_number', name='uq_supplier_parts_supplier_manufacturer_part_number'),
    schema='erp'
    )
    op.create_index('ix_supplier_parts_eol_date', 'supplier_parts', ['eol_date'], unique=False, schema='erp')
    op.create_index('ix_supplier_parts_part_number', 'supplier_parts', ['part_number'], unique=False, schema='erp')
    op.create_index('ix_supplier_parts_part_number_qualification_status', 'supplier_parts', ['part_number', 'qualification_status'], unique=False, schema='erp')
    op.create_index('ix_supplier_parts_supplier_id', 'supplier_parts', ['supplier_id'], unique=False, schema='erp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_parts_supplier_id', table_name='supplier_parts', schema='erp')
    op.drop_index('ix_supplier_parts_part_number_qualification_status', table_name='supplier_parts', schema='erp')
    op.drop_index('ix_supplier_parts_part_number', table_name='supplier_parts', schema='erp')
    op.drop_index('ix_supplier_parts_eol_date', table_name='supplier_parts', schema='erp')
    op.drop_table('supplier_parts', schema='erp')
    op.drop_index('ix_suppliers_status', table_name='suppliers', schema='erp')
    op.drop_table('suppliers', schema='erp')
    op.drop_index('ix_inventory_balances_plant_code', table_name='inventory_balances', schema='erp')
    op.drop_index('ix_inventory_balances_part_number_revision_code', table_name='inventory_balances', schema='erp')
    op.drop_index('ix_inventory_balances_part_number', table_name='inventory_balances', schema='erp')
    op.drop_table('inventory_balances', schema='erp')
    # ### end Alembic commands ###
