"""add inventory balance created at

Adds ``erp.inventory_balances.created_at`` so the table follows the general
rule of design doc v0.4 section 25 (every main table carries ``created_at``),
with the same definition used by erp.suppliers and erp.supplier_parts:
``timestamptz NOT NULL DEFAULT now()``.

The revision id is deliberately short: Alembic stores it in
``alembic_version.version_num``, which is ``varchar(32)`` by default, so a
37-character id such as "0003_add_inventory_balance_created_at" makes the
upgrade fail with StringDataRightTruncation. The file name keeps the full
wording, the revision id does not.

Revision ID: 0003_add_inventory_created_at
Revises: 0002_create_erp_master_tables
Create Date: 2026-09-20 19:32:34.489998

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003_add_inventory_created_at'
down_revision: str | Sequence[str] | None = '0002_create_erp_master_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_balances', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='erp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_balances', 'created_at', schema='erp')
    # ### end Alembic commands ###
