"""create purchase tables

Creates the purchase order tables of design doc v0.4: erp.purchase_orders
(section 29) and erp.purchase_order_lines (section 30).

purchase_orders is created before purchase_order_lines so the foreign key
target exists; the downgrade drops them in the opposite order.

Revision ID: 0004_purchase_tables
Revises: 0003_add_inventory_created_at
Create Date: 2026-09-20 19:45:32.160652

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004_purchase_tables'
down_revision: str | Sequence[str] | None = '0003_add_inventory_created_at'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'OPEN', 'PARTIALLY_RECEIVED', 'COMPLETED', 'CANCELLED', 'BLOCKED')", name='ck_purchase_orders_status'),
    sa.ForeignKeyConstraint(['supplier_id'], ['erp.suppliers.supplier_id'], name='fk_purchase_orders_supplier_id_suppliers', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('po_id'),
    sa.UniqueConstraint('po_number', name='uq_purchase_orders_po_number'),
    schema='erp'
    )
    op.create_index('ix_purchase_orders_expected_date', 'purchase_orders', ['expected_date'], unique=False, schema='erp')
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False, schema='erp')
    op.create_index('ix_purchase_orders_supplier_id', 'purchase_orders', ['supplier_id'], unique=False, schema='erp')
    op.create_table('purchase_order_lines',
    sa.Column('po_line_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('revision_code', sa.String(length=16), nullable=False),
    sa.Column('ordered_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_number > 0', name='ck_purchase_order_lines_line_number_positive'),
    sa.CheckConstraint('ordered_qty > 0', name='ck_purchase_order_lines_ordered_qty_positive'),
    sa.CheckConstraint('received_qty <= ordered_qty', name='ck_purchase_order_lines_received_qty_lte_ordered'),
    sa.CheckConstraint('received_qty >= 0', name='ck_purchase_order_lines_received_qty_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_purchase_order_lines_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['po_id'], ['erp.purchase_orders.po_id'], name='fk_purchase_order_lines_po_id_purchase_orders', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('po_line_id'),
    sa.UniqueConstraint('po_id', 'line_number', name='uq_purchase_order_lines_po_id_line_number'),
    schema='erp'
    )
    op.create_index('ix_purchase_order_lines_expected_date', 'purchase_order_lines', ['expected_date'], unique=False, schema='erp')
    op.create_index('ix_purchase_order_lines_part_number', 'purchase_order_lines', ['part_number'], unique=False, schema='erp')
    op.create_index('ix_purchase_order_lines_part_number_revision_code', 'purchase_order_lines', ['part_number', 'revision_code'], unique=False, schema='erp')
    op.create_index('ix_purchase_order_lines_status', 'purchase_order_lines', ['status'], unique=False, schema='erp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_order_lines_status', table_name='purchase_order_lines', schema='erp')
    op.drop_index('ix_purchase_order_lines_part_number_revision_code', table_name='purchase_order_lines', schema='erp')
    op.drop_index('ix_purchase_order_lines_part_number', table_name='purchase_order_lines', schema='erp')
    op.drop_index('ix_purchase_order_lines_expected_date', table_name='purchase_order_lines', schema='erp')
    op.drop_table('purchase_order_lines', schema='erp')
    op.drop_index('ix_purchase_orders_supplier_id', table_name='purchase_orders', schema='erp')
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders', schema='erp')
    op.drop_index('ix_purchase_orders_expected_date', table_name='purchase_orders', schema='erp')
    op.drop_table('purchase_orders', schema='erp')
    # ### end Alembic commands ###
