"""create production tables

Creates the production tables of design doc v0.4: erp.production_orders
(section 31) and erp.production_material_requirements (section 32).

production_material_requirements holds the frozen BOM explosion result of a
released production order. It stores part_number, revision_code and the
quantities directly, so historical demand stays readable after the current BOM
in Neo4j changes; nothing in the schema links it back to the live BOM.

production_orders is created before production_material_requirements so the
foreign key target exists; the downgrade drops them in the opposite order.

Revision ID: 0005_production_tables
Revises: 0004_purchase_tables
Create Date: 2026-09-20 19:49:08.351257

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0005_production_tables'
down_revision: str | Sequence[str] | None = '0004_purchase_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_orders',
    sa.Column('production_order_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('product_part_number', sa.String(length=64), nullable=False),
    sa.Column('product_revision', sa.String(length=16), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('completed_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PLANNED', 'RELEASED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED')", name='ck_production_orders_status'),
    sa.CheckConstraint('completed_qty <= planned_qty', name='ck_production_orders_completed_qty_lte_planned'),
    sa.CheckConstraint('completed_qty >= 0', name='ck_production_orders_completed_qty_non_negative'),
    sa.CheckConstraint('planned_qty > 0', name='ck_production_orders_planned_qty_positive'),
    sa.CheckConstraint('planned_start <= planned_end', name='ck_production_orders_planned_window'),
    sa.PrimaryKeyConstraint('production_order_id'),
    sa.UniqueConstraint('order_number', name='uq_production_orders_order_number'),
    schema='erp'
    )
    op.create_index('ix_production_orders_planned_end', 'production_orders', ['planned_end'], unique=False, schema='erp')
    op.create_index('ix_production_orders_planned_start', 'production_orders', ['planned_start'], unique=False, schema='erp')
    op.create_index('ix_production_orders_product_part_number_product_revision', 'production_orders', ['product_part_number', 'product_revision'], unique=False, schema='erp')
    op.create_index('ix_production_orders_status', 'production_orders', ['status'], unique=False, schema='erp')
    op.create_table('production_material_requirements',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('production_order_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('revision_code', sa.String(length=16), nullable=False),
    sa.Column('required_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issued_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('issued_qty <= required_qty', name='ck_production_material_requirements_issued_qty_lte_required'),
    sa.CheckConstraint('issued_qty >= 0', name='ck_production_material_requirements_issued_qty_non_negative'),
    sa.CheckConstraint('line_number > 0', name='ck_production_material_requirements_line_number_positive'),
    sa.CheckConstraint('required_qty > 0', name='ck_production_material_requirements_required_qty_positive'),
    sa.CheckConstraint('reserved_qty <= required_qty', name='ck_production_material_requirements_reserved_qty_lte_required'),
    sa.CheckConstraint('reserved_qty >= 0', name='ck_production_material_requirements_reserved_qty_non_negative'),
    sa.ForeignKeyConstraint(['production_order_id'], ['erp.production_orders.production_order_id'], name='fk_production_material_requirements_production_orders', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('requirement_id'),
    sa.UniqueConstraint('production_order_id', 'line_number', name='uq_production_material_requirements_order_line_number'),
    schema='erp'
    )
    op.create_index('ix_production_material_requirements_part_number_revision_code', 'production_material_requirements', ['part_number', 'revision_code'], unique=False, schema='erp')
    op.create_index('ix_production_material_requirements_production_order_id', 'production_material_requirements', ['production_order_id'], unique=False, schema='erp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_production_material_requirements_production_order_id', table_name='production_material_requirements', schema='erp')
    op.drop_index('ix_production_material_requirements_part_number_revision_code', table_name='production_material_requirements', schema='erp')
    op.drop_table('production_material_requirements', schema='erp')
    op.drop_index('ix_production_orders_status', table_name='production_orders', schema='erp')
    op.drop_index('ix_production_orders_product_part_number_product_revision', table_name='production_orders', schema='erp')
    op.drop_index('ix_production_orders_planned_start', table_name='production_orders', schema='erp')
    op.drop_index('ix_production_orders_planned_end', table_name='production_orders', schema='erp')
    op.drop_table('production_orders', schema='erp')
    # ### end Alembic commands ###
