"""create sales tables

Creates the sales order tables of design doc v0.4: erp.sales_orders
(section 33) and erp.sales_order_lines (section 34).

sales_orders is created before sales_order_lines so the foreign key target
exists; the downgrade drops them in the opposite order.

Revision ID: 0006_sales_tables
Revises: 0005_production_tables
Create Date: 2026-09-20 19:51:34.797845

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0006_sales_tables'
down_revision: str | Sequence[str] | None = '0005_production_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('customer_code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'OPEN', 'CONFIRMED', 'PARTIALLY_DELIVERED', 'COMPLETED', 'CANCELLED')", name='ck_sales_orders_status'),
    sa.PrimaryKeyConstraint('sales_order_id'),
    sa.UniqueConstraint('order_number', name='uq_sales_orders_order_number'),
    schema='erp'
    )
    op.create_index('ix_sales_orders_customer_code', 'sales_orders', ['customer_code'], unique=False, schema='erp')
    op.create_index('ix_sales_orders_requested_delivery_date', 'sales_orders', ['requested_delivery_date'], unique=False, schema='erp')
    op.create_index('ix_sales_orders_status', 'sales_orders', ['status'], unique=False, schema='erp')
    op.create_table('sales_order_lines',
    sa.Column('sales_order_line_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_part_number', sa.String(length=64), nullable=False),
    sa.Column('product_revision', sa.String(length=16), nullable=False),
    sa.Column('ordered_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('delivered_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delivered_qty <= ordered_qty', name='ck_sales_order_lines_delivered_qty_lte_ordered'),
    sa.CheckConstraint('delivered_qty >= 0', name='ck_sales_order_lines_delivered_qty_non_negative'),
    sa.CheckConstraint('line_number > 0', name='ck_sales_order_lines_line_number_positive'),
    sa.CheckConstraint('ordered_qty > 0', name='ck_sales_order_lines_ordered_qty_positive'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['erp.sales_orders.sales_order_id'], name='fk_sales_order_lines_sales_order_id_sales_orders', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sales_order_line_id'),
    sa.UniqueConstraint('sales_order_id', 'line_number', name='uq_sales_order_lines_sales_order_id_line_number'),
    schema='erp'
    )
    op.create_index('ix_sales_order_lines_product_part_number_product_revision', 'sales_order_lines', ['product_part_number', 'product_revision'], unique=False, schema='erp')
    op.create_index('ix_sales_order_lines_requested_delivery_date', 'sales_order_lines', ['requested_delivery_date'], unique=False, schema='erp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_order_lines_requested_delivery_date', table_name='sales_order_lines', schema='erp')
    op.drop_index('ix_sales_order_lines_product_part_number_product_revision', table_name='sales_order_lines', schema='erp')
    op.drop_table('sales_order_lines', schema='erp')
    op.drop_index('ix_sales_orders_status', table_name='sales_orders', schema='erp')
    op.drop_index('ix_sales_orders_requested_delivery_date', table_name='sales_orders', schema='erp')
    op.drop_index('ix_sales_orders_customer_code', table_name='sales_orders', schema='erp')
    op.drop_table('sales_orders', schema='erp')
    # ### end Alembic commands ###
