"""create ecm core tables

Creates the first engineering change tables of design doc v0.4:
ecm.change_cases (section 35), ecm.engineering_change_requests (section 36)
and ecm.change_impacts (section 37).

The upgrade follows the case -> request -> impact chain so every foreign key
target exists; the downgrade drops them in the opposite order.

Revision ID: 0007_ecm_core
Revises: 0006_sales_tables
Create Date: 2026-09-20 19:54:15.398358

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0007_ecm_core'
down_revision: str | Sequence[str] | None = '0006_sales_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_cases',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=40), nullable=False),
    sa.Column('case_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('raw_event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("case_type IN ('SUPPLIER_EOL', 'QUALITY_ISSUE', 'CUSTOMER_CHANGE', 'COST_REDUCTION', 'REGULATORY_CHANGE')", name='ck_change_cases_case_type'),
    sa.CheckConstraint("status IN ('RECEIVED', 'ANALYZING', 'PLANNING', 'WAITING_APPROVAL', 'APPROVED', 'EXECUTING', 'COMPLETED', 'REJECTED', 'FAILED', 'CANCELLED')", name='ck_change_cases_status'),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('case_number', name='uq_change_cases_case_number'),
    sa.UniqueConstraint('idempotency_key', name='uq_change_cases_idempotency_key'),
    schema='ecm'
    )
    op.create_index('ix_change_cases_case_type', 'change_cases', ['case_type'], unique=False, schema='ecm')
    op.create_index('ix_change_cases_created_at', 'change_cases', ['created_at'], unique=False, schema='ecm')
    op.create_index('ix_change_cases_status', 'change_cases', ['status'], unique=False, schema='ecm')
    op.create_table('engineering_change_requests',
    sa.Column('ecr_id', sa.UUID(), nullable=False),
    sa.Column('ecr_number', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('subject_part_number', sa.String(length=64), nullable=False),
    sa.Column('subject_revision_code', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_engineering_change_requests_priority'),
    sa.CheckConstraint("status IN ('DRAFT', 'OPEN', 'ANALYZING', 'PLANNING', 'WAITING_APPROVAL', 'APPROVED', 'REJECTED', 'CLOSED')", name='ck_engineering_change_requests_status'),
    sa.ForeignKeyConstraint(['case_id'], ['ecm.change_cases.case_id'], name='fk_engineering_change_requests_case_id_change_cases', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ecr_id'),
    sa.UniqueConstraint('case_id', name='uq_engineering_change_requests_case_id'),
    sa.UniqueConstraint('ecr_number', name='uq_engineering_change_requests_number'),
    schema='ecm'
    )
    op.create_index('ix_engineering_change_requests_created_at', 'engineering_change_requests', ['created_at'], unique=False, schema='ecm')
    op.create_index('ix_engineering_change_requests_priority', 'engineering_change_requests', ['priority'], unique=False, schema='ecm')
    op.create_index('ix_engineering_change_requests_status', 'engineering_change_requests', ['status'], unique=False, schema='ecm')
    op.create_index('ix_engineering_change_requests_subject_part_number', 'engineering_change_requests', ['subject_part_number'], unique=False, schema='ecm')
    op.create_table('change_impacts',
    sa.Column('impact_id', sa.UUID(), nullable=False),
    sa.Column('ecr_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_key', sa.String(length=150), nullable=False),
    sa.Column('impact_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("object_type IN ('PART', 'PART_REVISION', 'ASSEMBLY', 'PRODUCT', 'BOM_VERSION', 'INVENTORY', 'PURCHASE_ORDER', 'PRODUCTION_ORDER', 'SALES_ORDER')", name='ck_change_impacts_object_type'),
    sa.CheckConstraint("severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_change_impacts_severity'),
    sa.ForeignKeyConstraint(['ecr_id'], ['ecm.engineering_change_requests.ecr_id'], name='fk_change_impacts_ecr_id_engineering_change_requests', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('impact_id'),
    sa.UniqueConstraint('analysis_run_id', 'object_type', 'object_key', 'impact_type', name='uq_change_impacts_analysis_run_object_impact'),
    schema='ecm'
    )
    op.create_index('ix_change_impacts_analysis_run_id', 'change_impacts', ['analysis_run_id'], unique=False, schema='ecm')
    op.create_index('ix_change_impacts_ecr_id', 'change_impacts', ['ecr_id'], unique=False, schema='ecm')
    op.create_index('ix_change_impacts_object_type_object_key', 'change_impacts', ['object_type', 'object_key'], unique=False, schema='ecm')
    op.create_index('ix_change_impacts_severity', 'change_impacts', ['severity'], unique=False, schema='ecm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_change_impacts_severity', table_name='change_impacts', schema='ecm')
    op.drop_index('ix_change_impacts_object_type_object_key', table_name='change_impacts', schema='ecm')
    op.drop_index('ix_change_impacts_ecr_id', table_name='change_impacts', schema='ecm')
    op.drop_index('ix_change_impacts_analysis_run_id', table_name='change_impacts', schema='ecm')
    op.drop_table('change_impacts', schema='ecm')
    op.drop_index('ix_engineering_change_requests_subject_part_number', table_name='engineering_change_requests', schema='ecm')
    op.drop_index('ix_engineering_change_requests_status', table_name='engineering_change_requests', schema='ecm')
    op.drop_index('ix_engineering_change_requests_priority', table_name='engineering_change_requests', schema='ecm')
    op.drop_index('ix_engineering_change_requests_created_at', table_name='engineering_change_requests', schema='ecm')
    op.drop_table('engineering_change_requests', schema='ecm')
    op.drop_index('ix_change_cases_status', table_name='change_cases', schema='ecm')
    op.drop_index('ix_change_cases_created_at', table_name='change_cases', schema='ecm')
    op.drop_index('ix_change_cases_case_type', table_name='change_cases', schema='ecm')
    op.drop_table('change_cases', schema='ecm')
    # ### end Alembic commands ###
