"""create strategy tables

Creates the strategy planning tables of design doc v0.4: ecm.change_strategies
(section 38) and ecm.change_strategy_actions (section 39).

change_strategies is created before change_strategy_actions so the foreign key
target exists; the downgrade drops them in the opposite order.

Revision ID: 0008_strategy_tables
Revises: 0007_ecm_core
Create Date: 2026-09-20 19:58:26.062563

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0008_strategy_tables'
down_revision: str | Sequence[str] | None = '0007_ecm_core'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_strategies',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('ecr_id', sa.UUID(), nullable=False),
    sa.Column('strategy_code', sa.String(length=30), nullable=False),
    sa.Column('strategy_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('replacement_part_number', sa.String(length=64), nullable=True),
    sa.Column('replacement_revision_code', sa.String(length=16), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('cost_delta', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('inventory_writeoff_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('CANDIDATE', 'RECOMMENDED', 'SELECTED', 'REJECTED', 'SUPERSEDED')", name='ck_change_strategies_status'),
    sa.CheckConstraint("strategy_type IN ('IMMEDIATE_REPLACEMENT', 'INVENTORY_RUN_OUT', 'SPLIT_EFFECTIVITY', 'LAST_TIME_BUY')", name='ck_change_strategies_strategy_type'),
    sa.CheckConstraint('inventory_writeoff_cost >= 0', name='ck_change_strategies_writeoff_cost_non_negative'),
    sa.ForeignKeyConstraint(['ecr_id'], ['ecm.engineering_change_requests.ecr_id'], name='fk_change_strategies_ecr_id_engineering_change_requests', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('strategy_id'),
    sa.UniqueConstraint('ecr_id', 'strategy_code', name='uq_change_strategies_ecr_id_strategy_code'),
    schema='ecm'
    )
    op.create_table('change_strategy_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_key', sa.String(length=150), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('CREATE_BOM_REDLINE', 'SET_EFFECTIVITY', 'BLOCK_PRODUCTION_ORDER', 'NOTIFY_OWNER', 'CREATE_ECO_DRAFT')", name='ck_change_strategy_actions_action_type'),
    sa.ForeignKeyConstraint(['strategy_id'], ['ecm.change_strategies.strategy_id'], name='fk_change_strategy_actions_strategy_id_change_strategies', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('strategy_id', 'sequence_no', name='uq_change_strategy_actions_strategy_id_sequence_no'),
    schema='ecm'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_strategy_actions', schema='ecm')
    op.drop_table('change_strategies', schema='ecm')
    # ### end Alembic commands ###
