"""create remaining ecm tables

Creates the remaining ECM tables of design doc v0.4:
ecm.change_reviews (section 40), ecm.engineering_change_orders (section 41),
ecm.approval_records (section 42), ecm.bom_redlines (section 43),
ecm.bom_redline_lines (section 44) and ecm.execution_jobs (section 45).

Creation order follows the foreign key chain (engineering_change_orders before
its dependants, bom_redlines before bom_redline_lines); the downgrade drops
them in the opposite order.

Revision ID: 0010_ecm_remaining
Revises: 0009_action_seq_check
Create Date: 2026-09-20 20:07:19.861813

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0010_ecm_remaining'
down_revision: str | Sequence[str] | None = '0009_action_seq_check'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('review_run_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('evidence_complete', sa.Boolean(), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('PASS', 'REWORK', 'HUMAN_REVIEW', 'BLOCK')", name='ck_change_reviews_decision'),
    sa.ForeignKeyConstraint(['strategy_id'], ['ecm.change_strategies.strategy_id'], name='fk_change_reviews_strategy_id_change_strategies', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('review_id'),
    schema='ecm'
    )
    op.create_table('engineering_change_orders',
    sa.Column('eco_id', sa.UUID(), nullable=False),
    sa.Column('eco_number', sa.String(length=40), nullable=False),
    sa.Column('ecr_id', sa.UUID(), nullable=False),
    sa.Column('selected_strategy_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'WAITING_APPROVAL', 'APPROVED', 'EXECUTING', 'EXECUTED', 'EXECUTION_FAILED', 'REJECTED', 'CANCELLED')", name='ck_engineering_change_orders_status'),
    sa.ForeignKeyConstraint(['ecr_id'], ['ecm.engineering_change_requests.ecr_id'], name='fk_engineering_change_orders_ecr_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_strategy_id'], ['ecm.change_strategies.strategy_id'], name='fk_engineering_change_orders_selected_strategy_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('eco_id'),
    sa.UniqueConstraint('eco_number', name='uq_engineering_change_orders_eco_number'),
    schema='ecm'
    )
    op.create_table('approval_records',
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('eco_id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.String(length=40), nullable=False),
    sa.Column('approver_id', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED', 'REWORK')", name='ck_approval_records_decision'),
    sa.ForeignKeyConstraint(['eco_id'], ['ecm.engineering_change_orders.eco_id'], name='fk_approval_records_eco_id_engineering_change_orders', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('approval_id'),
    schema='ecm'
    )
    op.create_table('bom_redlines',
    sa.Column('redline_id', sa.UUID(), nullable=False),
    sa.Column('eco_id', sa.UUID(), nullable=False),
    sa.Column('source_bom_version_id', sa.UUID(), nullable=False),
    sa.Column('target_bom_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED', 'APPLIED', 'REJECTED', 'FAILED')", name='ck_bom_redlines_status'),
    sa.ForeignKeyConstraint(['eco_id'], ['ecm.engineering_change_orders.eco_id'], name='fk_bom_redlines_eco_id_engineering_change_orders', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('redline_id'),
    schema='ecm'
    )
    op.create_table('execution_jobs',
    sa.Column('execution_job_id', sa.UUID(), nullable=False),
    sa.Column('eco_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name='ck_execution_jobs_status'),
    sa.ForeignKeyConstraint(['eco_id'], ['ecm.engineering_change_orders.eco_id'], name='fk_execution_jobs_eco_id_engineering_change_orders', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('execution_job_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_execution_jobs_idempotency_key'),
    schema='ecm'
    )
    op.create_table('bom_redline_lines',
    sa.Column('redline_line_id', sa.UUID(), nullable=False),
    sa.Column('redline_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('source_bom_line_id', sa.UUID(), nullable=True),
    sa.Column('old_part_number', sa.String(length=64), nullable=True),
    sa.Column('old_revision_code', sa.String(length=16), nullable=True),
    sa.Column('new_part_number', sa.String(length=64), nullable=True),
    sa.Column('new_revision_code', sa.String(length=16), nullable=True),
    sa.Column('old_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('new_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('ADD', 'REMOVE', 'REPLACE', 'UPDATE_QUANTITY')", name='ck_bom_redline_lines_action_type'),
    sa.ForeignKeyConstraint(['redline_id'], ['ecm.bom_redlines.redline_id'], name='fk_bom_redline_lines_redline_id_bom_redlines', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('redline_line_id'),
    schema='ecm'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bom_redline_lines', schema='ecm')
    op.drop_table('execution_jobs', schema='ecm')
    op.drop_table('bom_redlines', schema='ecm')
    op.drop_table('approval_records', schema='ecm')
    op.drop_table('engineering_change_orders', schema='ecm')
    op.drop_table('change_reviews', schema='ecm')
    # ### end Alembic commands ###
