"""create agent audit tables

Creates the remaining first-phase tables of design doc v0.4:
agent.agent_runs (section 46), agent.agent_steps (section 47),
agent.tool_calls (section 48) and audit.audit_events (section 50), and adds
the missing ck_bom_redline_lines_sequence_no_positive constraint to the
already existing ecm.bom_redline_lines table.

The redline CHECK is written by hand: Alembic only loads the
``alembic.autogenerate.*`` plugins by default, so the check constraint
comparison from ``alembic.ext.checkconstraint_byname`` is not active and
autogenerate cannot see a new CHECK on an existing table.

Revision ID: 0011_agent_audit
Revises: 0010_ecm_remaining
Create Date: 2026-09-20 20:11:39.505886

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0011_agent_audit'
down_revision: str | Sequence[str] | None = '0010_ecm_remaining'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Added by hand: autogenerate cannot detect a new CHECK on an existing table.
    op.create_check_constraint(
        "ck_bom_redline_lines_sequence_no_positive",
        "bom_redline_lines",
        "sequence_no > 0",
        schema="ecm",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('workflow_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING', 'WAITING_HUMAN', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name='ck_agent_runs_status'),
    sa.PrimaryKeyConstraint('run_id'),
    schema='agent'
    )
    op.create_index('ix_agent_runs_case_id', 'agent_runs', ['case_id'], unique=False, schema='agent')
    op.create_index('ix_agent_runs_started_at', 'agent_runs', ['started_at'], unique=False, schema='agent')
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False, schema='agent')
    op.create_table('audit_events',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=60), nullable=False),
    sa.Column('object_id', sa.String(length=150), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('HUMAN', 'AGENT', 'SYSTEM')", name='ck_audit_events_actor_type'),
    sa.PrimaryKeyConstraint('audit_id'),
    schema='audit'
    )
    op.create_index('ix_audit_events_actor_type', 'audit_events', ['actor_type'], unique=False, schema='audit')
    op.create_index('ix_audit_events_case_id', 'audit_events', ['case_id'], unique=False, schema='audit')
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False, schema='audit')
    op.create_index('ix_audit_events_object_type_object_id', 'audit_events', ['object_type', 'object_id'], unique=False, schema='audit')
    op.create_index('ix_audit_events_run_id', 'audit_events', ['run_id'], unique=False, schema='audit')
    op.create_table('agent_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent.agent_runs.run_id'], name='fk_agent_steps_run_id_agent_runs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('step_id'),
    schema='agent'
    )
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_mode', sa.String(length=10), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'BLOCKED')", name='ck_tool_calls_status'),
    sa.CheckConstraint("tool_mode IN ('READ', 'WRITE')", name='ck_tool_calls_tool_mode'),
    sa.ForeignKeyConstraint(['run_id'], ['agent.agent_runs.run_id'], name='fk_tool_calls_run_id_agent_runs', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['step_id'], ['agent.agent_steps.step_id'], name='fk_tool_calls_step_id_agent_steps', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tool_call_id'),
    schema='agent'
    )
    op.create_index('ix_tool_calls_agent_name', 'tool_calls', ['agent_name'], unique=False, schema='agent')
    op.create_index('ix_tool_calls_created_at', 'tool_calls', ['created_at'], unique=False, schema='agent')
    op.create_index('ix_tool_calls_run_id', 'tool_calls', ['run_id'], unique=False, schema='agent')
    op.create_index('ix_tool_calls_tool_name', 'tool_calls', ['tool_name'], unique=False, schema='agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_tool_name', table_name='tool_calls', schema='agent')
    op.drop_index('ix_tool_calls_run_id', table_name='tool_calls', schema='agent')
    op.drop_index('ix_tool_calls_created_at', table_name='tool_calls', schema='agent')
    op.drop_index('ix_tool_calls_agent_name', table_name='tool_calls', schema='agent')
    op.drop_table('tool_calls', schema='agent')
    op.drop_table('agent_steps', schema='agent')
    op.drop_index('ix_audit_events_run_id', table_name='audit_events', schema='audit')
    op.drop_index('ix_audit_events_object_type_object_id', table_name='audit_events', schema='audit')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events', schema='audit')
    op.drop_index('ix_audit_events_case_id', table_name='audit_events', schema='audit')
    op.drop_index('ix_audit_events_actor_type', table_name='audit_events', schema='audit')
    op.drop_table('audit_events', schema='audit')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs', schema='agent')
    op.drop_index('ix_agent_runs_started_at', table_name='agent_runs', schema='agent')
    op.drop_index('ix_agent_runs_case_id', table_name='agent_runs', schema='agent')
    op.drop_table('agent_runs', schema='agent')
    op.drop_constraint(
        "ck_bom_redline_lines_sequence_no_positive",
        "bom_redline_lines",
        type_="check",
        schema="ecm",
    )
    # ### end Alembic commands ###
